### ISSUE TITLE
Создать приложение todo

### ISSUE THREAD

**Issue by Yashiandr** [Yashiandr/simpletodolist#1]
Создать приложение todo-list по [данному](https://www.figma.com/file/nw7Wwwf9Eb9u97sZJR69JV/Simple-ToDo-List-Design?type=design&node-id=0%3A1&mode=design&t=OTbXB6DCyiRGcoQm-1) шаблону 

В приложении имеются компоненты:

- [ ] - Header
- [ ] - Input
- [ ] - Tabel
- [ ] - Action
- [ ] - Dialog
- [ ] - FormInput
- [ ] - Button
- [ ] - Suggest
- [ ] - ThemeSwitcher
- [ ] - Body
- [ ] - DataFlow
- [ ] - Info

В приложении должно быть реализовано: 

- [ ] - Выбор темы между светлой и темной,
- [ ] - Добавление в локальном хранилище созданных целей,
- [ ] - Отображение из локального хранилища списка целей,
- [ ] - Отображение выполненных целей как перечеркнутых,
- [ ] - Возможность удалять или редактировать цели.
